### ISSUE TITLE
Upgrade Chimeverse to Converse 5.0.0

### ISSUE THREAD

**Issue by Nyco** [nick-denry/Chimeverse#1]
Hello,

It would be nice to upgrade to the latest release so far of Converse, that is version 5.0.0: https://github.com/conversejs/converse.js/releases/tag/v5.0.0

Thanks a lot

**Comment by nick-denry** [comment]
Hi!

Thank you. I was waiting for the Converse 5.0.0 too to rebuld app with the new `embedded` view mode. I'll take a look for what 5.0.0 is now.

**Comment by Nyco** [comment]
Oops, 5.0.1 is available now :)
https://github.com/conversejs/converse.js/releases/tag/v5.0.1
Thanks!

**Comment by Nyco** [comment]
And boom! :)
https://github.com/conversejs/converse.js/releases/tag/v6.0.0

Hey Nick, please contact me directly, we might have something for you...

**Comment by nick-denry** [comment]
Closed via https://github.com/nick-denry/Chimeverse/commit/db9428b23c5b08b54a6d671a86866ac8d824c6bc
