### ISSUE TITLE
Add more platforms by using Cordova's Electron support?

### ISSUE THREAD

**Issue by poVoq** [nick-denry/Chimeverse#17]
Might or might not be a simple port, but would potentially expand it to mobile platforms:
https://cordova.apache.org/docs/en/latest/guide/platforms/electron/index.html

I have been playing around with ConverseJS on mobile, and with a few CSS fixes it works quite well with my Ubuntu Touch port.

**Comment by nick-denry** [comment]
Hi, @poVoq!

Doesn't UBports support Electron? Does it support Cordova?

**Comment by poVoq** [comment]
There is an old unmaintained Cordova port for it, but it is not working very well. But I am still hopeful it will get updated at some point.

Electron is only supported via the Libertine container to emulate a desktop Ubuntu PC.

**Comment by nick-denry** [comment]
Sounds not that much promising. Is your goal a UBports xmpp client? Is something wrong or missing with your Ubuntu Touch port?

**Comment by poVoq** [comment]
No, my UT port runs fine. I was rather thinking about iOS and Android (and any other platforms supported by Cordova).

**Comment by nick-denry** [comment]
Ok I see now. Could you please explain why do you suggest that?

Technically it's possible to use the app code with Cordova _instead_ of Electron as far as the app itself is mainly an AngularJS project. The main problem with a Cordova is that Cordova app will require to run as background service to keep connection and I'm absolutely not sure if converse js connection will be stable in that case, cause of auto_reconnect and so on. A lot of tests needed.

**Comment by poVoq** [comment]
Cordova has Electron build in since recently, so a single codebase would give all the platforms.

Not sure about the background service stuff, but my experience with autoreconect and smacks seem to indicate that ConverseJS can manage it.

**Comment by nick-denry** [comment]
I don't get it. As far as I understand Cordova Electron is a tool for a building desktop app from existing Cordova project to Electron platform, but not vice versa. So adding iOS and Android will require full project to be Cordova project instead of Electron. Am I wrong?

**Comment by poVoq** [comment]
Yes, but I imaging porting over a project from pure Electron to Cordova managed Electron shouldn't be very difficult and you get a lot in return, probably even in the Electron version.

**Comment by nick-denry** [comment]
Ok, thank you @poVoq. I'll try some tests first.
