### ISSUE TITLE
About dialog box

### ISSUE THREAD

**Issue by Nyco** [nick-denry/Chimeverse#2]
Hello,

It would be nice to have an "About" dialog box, from drop down menu "Chimeverse" that contains software versions for Chimeverse itself, but also Converse, and probably Electron.

Thanks

**Comment by nick-denry** [comment]
Closed via https://github.com/nick-denry/Chimeverse/commit/5d6af51c6bbc866f8331946666961bdd573b00dc and https://github.com/nick-denry/Chimeverse/commit/bd3e4f6ba378c1d0c712077989110915f41f4d45
