### ISSUE TITLE
If I open the MAC app I get white screen

### ISSUE THREAD

**Issue by jnaeff** [nick-denry/Chimeverse#23]
Hi,

I installed the latest version. Only when I open the app I get a white screen. What do I do wrong.

![Screenshot #100](https://user-images.githubusercontent.com/1419331/84046068-e7198d00-a9a9-11ea-9042-47338435589e.png)

**Comment by nick-denry** [comment]
Hi! 

I've just tested a fresh install of the https://github.com/nick-denry/Chimeverse/releases/download/v0.1.54/Chimeverse-0.1.54_x64.dmg release version and it works just fine on my macOS Mojave.

Possible troubleshooting step is:

1. Try to redownload and reinstall app via deleting it from your "Applications" directory.

If that not helps:

1. Could you please show about screen from "Chimeverse" -> "About Chimeverse" menu item?
2. What version of macOS do you use?
3. Do you have fresh install or upgrade from previous version?

Thank you.

**Comment by jnaeff** [comment]
1. Is also white
2. 10.15.5
3. Fresh install

Still the same issue. 

You also thank you :)

**Comment by nick-denry** [comment]
Well, there is an issue https://github.com/electron/electron/issues/18660 related to Electron project about macOS 10.15.5 Catalina support.

As by fast googling It seems that Electron-based apps require additional things like application notarization, etc. to run under macOS Catalina. I don't have one, but I will work on this issue at some further releases.

I also suppose you're able to run application via terminal and npm following [this README steps section](https://github.com/nick-denry/Chimeverse#run-with-npm). Give it a try.

**Comment by nick-denry** [comment]
Another temporary workaround could be to run `sudo spctl --master-disable` according to [this comment](https://github.com/desktop/desktop/issues/8506#issuecomment-547107951) at github desktop project issue, untill app will be notarized.

Please provide feedback if you're able. Thanks in advance.

**Comment by jnaeff** [comment]
Hi Nick, I tried above option it didn't make a change.

**Comment by nick-denry** [comment]
I guess now that you're faced with the same issue as #24, so it's not about notarization. Please check if [the new release](https://github.com/nick-denry/Chimeverse/releases/tag/v0.1.55) fix this for you.

If not, I've added the `debug info` item to the help menu, so we could collect more information about what happens (maybe).

**Comment by jnaeff** [comment]
It works !

**Comment by jnaeff** [comment]
Great are you maybee also intrested todo some freelance work?

**Comment by nick-denry** [comment]
> It works !

Glad to hear that.

> Great are you maybee also intrested todo some freelance work?

Nope, thank you.
