### ISSUE TITLE
Chimeverse fails to load due to missing locale files

### ISSUE THREAD

**Issue by bremensaki** [nick-denry/Chimeverse#24]
On my Debian system, Chimeverse loads a blank, white page and fails to run. After doing a local build and investigating I've found that commenting out the locales and locales/dayjs lines in index.html makes Chimeverse load and function as expected.

`Uncaught Error: Cannot find module './node_modules/converse.js/dist/locales/en-GB-LC_MESSAGES-converse-po.js'`

Should there be a test to see if these files exist before attempting to load them? The dayjs file for en-GB does exist, but it's lower case so also won't be found.

**Comment by nick-denry** [comment]
Hi!

Fixed by https://github.com/nick-denry/Chimeverse/commit/9a8d03a30e145c4d72feee99aed1bf62e820a9bd. Tested with `en_GB`, `fr_FR` and `ru_RU` locales. Please also check on your system if possible. Thank you.

**Comment by bremensaki** [comment]
Yep, it starts up normally on my system when built from master now.

**Comment by nick-denry** [comment]
Many thanks for your help. Fix will be available with next release soon.
