### ISSUE TITLE
Could you please also make a simple tar.gz release for non-debian Linux?

### ISSUE THREAD

**Issue by poVoq** [nick-denry/Chimeverse#28]
Could you please also make a simple tar.gz release for non-debian Linux?

Thanks :)

**Comment by ghost** [comment]
AppImage and Flatpak might be good alternatives for universal support for different distributions.

**Comment by nick-denry** [comment]
Closed due to the new [Converse Desktop v0.1.0](https://github.com/conversejs/converse-desktop/releases).
