### ISSUE TITLE
Would you be interested in making this the official Electron version of Converse.js?

### ISSUE THREAD

**Issue by jcbrand** [nick-denry/Chimeverse#30]
Hi Nick

Great job on making an Electron port of Converse.js.  Would you be interested in making Chimeverse the official Electron version of Converse.js?

To do so, would mean moving the repository to https://github.com/conversejs/converse-electron and renaming it to something like `Converse Desktop`.

In addition to that, would you be open to changing the license to the Mozilla Public License v2 (same as the other Converse.js software)? Looks like you authored all the commits so far, so relicensing shouldn't be difficult.

I look forward to your reply. You can find my email address in my Github profile: https://github.com/jcbrand

UPDATE: Just to be clear, you would still be the lead dev on this project and pull requests will go to you.

**Comment by nick-denry** [comment]
Hi @jcbrand 

Thank you for your message and for Converse.js too. Whether I'll be lead dev or not I'd like to participate in things that could make xmpp community stronger.

I have a question about licensing, please tell me. Chimeverse licensed under GPL3.0 cause of using libsignal for OMEMO, and if we change license it wont be possible to use libsignal, right?

Is there a way to keep this functionality like dual licensing or an "official" and "unofficial" repos or build instructions, etc?

**Comment by jcbrand** [comment]
Ah ok, I didn't think of libsignal.

Well, MPLv2 licensed code is compatible with GPLv3. If there are GPLv3 libs included, then the MPLv2 code automatically becomes GPLv3 as well.

What we can do is to load libsignal dynamically if OMEMO is enabled via the configuration settings. So if OMEMO is disabled, the code is MPLv2 and if OMEMO is enabled the code is GPLv3.

**Comment by nick-denry** [comment]
Well. Than I'll check how the dynamic loading of libsignal will work first.

**Comment by jcbrand** [comment]
I think this needs to be done in converse core, similar to how the emojis.json file is loaded dynamically.

**Comment by nick-denry** [comment]
Agree, that's would be even better and more easily to maintain. What is your vision about next steps before publishing `Converse Desktop`?

**Comment by jcbrand** [comment]
I guess it would make sense to first release Converse 7.

**Comment by jcbrand** [comment]
Hi @nick-denry, I've thought a bit more about loading libsignal dynamically. It might still make sense from a technical perspective when using Converse in the browser, in order to keep the initial downloaded bundle small, but I don't think it really matters for the Electron build.

The reason being that you'd still have to bundle libsignal with the Electron-based executable, and if you didn't, then you'd have to download it from somewhere at runtime, which would have adverse security implications.

So I don't think loading libsignal dynamically is important or a requirement for Converse Desktop anymore.

Since the MPLv2 is compatible with the GPLv3, it would be enough to relicense the files in this repo to MVPLv2.
Then, the "vanilla" Converse Desktop will include libsignal and will therefore effectively be licensed under the GPLv3.

And if someone makes an Electron version without libsignal, then it'll be licensed under the MPLv2.

Sounds OK to you?

**Comment by nick-denry** [comment]
Hi. Sounds mostly OK.

> Since the MPLv2 is compatible with the GPLv3, it would be enough to relicense the files in this repo to MVPLv2.
> Then, the "vanilla" Converse Desktop will include libsignal and will therefore effectively be licensed under the GPLv3.

Could you please explain a bit more about "relicense the files in this repo"? How this could be done?

And do you mean binary builds by "vanilla" word?

P.S. I mean what should I exactly do next? :)

**Comment by jcbrand** [comment]
I'll move this repo to a new one in the converse organisation, and then once I'm done, you need to change the LICENSE file in the new repo to one that contains the MPLv2 license.

That commit has to come from you, because you authored all the files in this repo and therefore own the copyright (and the ability to relicense).

"vanilla" means the default, non-customized, non-modified Electron version of Converse. Like how vanilla ice cream is the "default" ice cream.

**Comment by jcbrand** [comment]
I created the repo here: https://github.com/conversejs/converse-desktop

**Comment by nick-denry** [comment]
Hi. Write you an email. Let's move there.
