### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [nick-denry/Chimeverse#8]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by nick-denry** [comment]
Hi, @Neustradamus !

Don't you think that [converse.js features page](https://conversejs.org/#features) is enough?

**Comment by Neustradamus** [comment]
@nick-denry: Thanks for your reply!
No because, No RFC, and XEPs have not the good name and VERSION is missing for each, example:
- XEP-XXXX v1.2

**Comment by nick-denry** [comment]
Unfortunately there is nothing to do with this issue as far as converse.js [README](https://github.com/conversejs/converse.js/#supported-xmpp-extensions) contains only XEP names, but not versions. Please reopen this issue (or create a new one) if converse.js info will be updated somewhen. Thank you.

**Comment by Neustradamus** [comment]
@nick-denry: Linked to:
- https://github.com/conversejs/converse.js/issues/1037
